import { skinAssetUrl } from './asset-url.ts'

// Generated by assets/boot-error/prepare.py.
export const MAID_BOOT_ERROR_LEFT = skinAssetUrl('4386aee80ebaa41f926096ae9e0378b08dbd3eaaa2ad6646ff8f50a3f480a7a9.webp')
export const MAID_BOOT_ERROR_RIGHT = skinAssetUrl('1183d4d3a2b122078d09b1d9c97e085696ae214694399f14ce407fc21d8f1ec1.webp')
