import { skinAssetUrl } from './asset-url.ts'

// Generated by scripts/build-maid-icons.py.
export const SLEEPY_32 = skinAssetUrl('c033e0ef8cca6b516489f4e2aab05dac758c54ea3cf20f246412f08735c2d7fc.png')
export const DELIGHTED_32 = skinAssetUrl('98f0e13da2ecb0913739d6fbe83026b66746263a9c1dab006ef1b73279b7d8de.png')
export const DELIGHTED_192 = skinAssetUrl('c433e0bc2e5a36cc0022eb05150691986b5086b749ceacc556ab71359438d5c4.png')
export const DELIGHTED_512 = skinAssetUrl('06eaf23edd8d5efcf8dfd2ff573307d92ad4422f4a5c022064e9659d34258b8d.png')
export const DETERMINED_32 = skinAssetUrl('fe8e1db21924622a0a3a38bd8fde3197d0f0ef2ba2b48c4665f5569013cd4f1d.png')
