"""Convert the supplied icon artwork to PNG/ICO and embed the runtime sizes."""
import base64
from collections import deque
from pathlib import Path

import numpy as np
from PIL import Image, ImageOps, ImageFilter, ImageDraw


def cutout(source, name):
    rgb = np.asarray(source.convert('RGB')).copy()
    height, width = rgb.shape[:2]
    # Flood only explicitly identified background regions: white clothing is
    # enclosed by dark ink, and the close-up's headband touches the image edge.
    pale = (rgb.min(axis=2) >= 235) & (np.ptp(rgb, axis=2) <= 25)
    seeds = [(0, 0), (width - 1, 0), (0, height - 1), (width - 1, height - 1)]
    holes = {
        'sleepy': [(0.815, 0.596), (0.167, 0.606)],
        'delighted': [(0.079, 0.802), (0.910, 0.734)],
        'determined': [],
    }
    seeds += [(int(x * width), int(y * height)) for x, y in holes[name]]
    background = np.zeros((height, width), dtype=bool)
    queue = deque()
    for x, y in seeds:
        if pale[y, x]:
            background[y, x] = True
            queue.append((x, y))
    while queue:
        x, y = queue.popleft()
        for nx, ny in ((x - 1, y), (x + 1, y), (x, y - 1), (x, y + 1)):
            if 0 <= nx < width and 0 <= ny < height and pale[ny, nx] and not background[ny, nx]:
                background[ny, nx] = True
                queue.append((nx, ny))
    # A one-pixel transition removes pale antialiasing without eroding linework.
    bg = Image.fromarray(background.astype('uint8') * 255)
    edge = np.asarray(bg.filter(ImageFilter.MaxFilter(3))) > 0
    alpha = np.full((height, width), 255, dtype='uint8')
    alpha[background] = 0
    transition = edge & ~background
    opacity = np.clip((255 - rgb.min(axis=2).astype(float)) / 64, 0, 1)
    alpha[transition] = np.rint(opacity[transition] * 255).astype('uint8')
    a = alpha.astype(float) / 255
    partial = (alpha > 0) & (alpha < 255)
    rgb[partial] = np.clip((rgb[partial].astype(float) - 255 * (1 - a[partial, None])) / a[partial, None], 0, 255)
    rgba = Image.fromarray(np.dstack((rgb, alpha)))
    return rgba

root = Path(__file__).resolve().parent.parent / 'maid-atelier'
assets = root / 'assets' / 'icons'
names = ('sleepy', 'delighted', 'determined')
entries = []
for name in names:
    with Image.open(assets / 'source' / f'{name}.png') as source:
        extracted = cutout(source, name)
        extracted.save(assets / f'{name}-cutout.png', optimize=True)
        content = ImageOps.contain(extracted.crop(extracted.getbbox()), (488, 488), Image.Resampling.LANCZOS)
        square = Image.new('RGBA', (512, 512))
        square.alpha_composite(content, ((512 - content.width) // 2, (512 - content.height) // 2))
        square.save(assets / f'{name}.ico', sizes=[(n, n) for n in (16, 24, 32, 48, 64, 128, 256)])
        for size in ((32, 192, 512) if name == 'delighted' else (32,)):
            path = assets / f'{name}-{size}.png'
            square.resize((size, size), Image.Resampling.LANCZOS).save(path, optimize=True)
            encoded = base64.b64encode(path.read_bytes()).decode('ascii')
            entries.append(f"export const {name.upper()}_{size} = 'data:image/png;base64,{encoded}'")

(root / 'src' / 'client' / 'icon-art.generated.ts').write_text(
    '// Generated by scripts/build-maid-icons.py.\n' + '\n'.join(entries) + '\n', encoding='utf-8')

# Review both light and dark surfaces without changing the delivered artwork.
preview = Image.new('RGB', (720, 520), '#f1f1f1')
draw = ImageDraw.Draw(preview)
draw.rectangle((0, 260, 720, 520), fill='#17213b')
for i, name in enumerate(names):
    with Image.open(assets / f'{name}.ico') as icon:
        icon = icon.convert('RGBA')
        for y in (0, 260):
            large = icon.resize((192, 192), Image.Resampling.LANCZOS)
            preview.paste(large, (i * 240 + 24, y + 8), large)
            for j, size in enumerate((16, 32, 48)):
                small = icon.resize((size, size), Image.Resampling.LANCZOS)
                preview.paste(small, (i * 240 + 28 + j * 64, y + 205), small)
preview.save(assets / 'preview.png')
